version: '2.3'
services:
  v2ray:
    image: v2ray/official
    container_name: v2ray
    restart: always
    volumes:
      - /root/config.json:/etc/v2ray/config.json
    ports:
      - "10808:10808"